kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.220.0.0/16"
  serviceSubnet: "10.225.0.0/16"
nodes:
 - role: control-plane
   image: kindest/node:v1.23.17 
 - role: worker
   image: kindest/node:v1.23.17
   extraPortMappings:
   - containerPort: 40000
     hostPort: 40000
     listenAddress: 127.0.0.1
     protocol: TCP
 - role: worker
   image: kindest/node:v1.23.17
   extraPortMappings:
   - containerPort: 40000
     hostPort: 40001
     listenAddress: 127.0.0.1
     protocol: TCP   
